//! The checked-in `schemas/*.json` must equal what the types generate —
//! the contract is derived from the code, never hand-edited. Fails when a
//! type change lands without `just schemas`.

use std::path::Path;

#[test]
fn checked_in_schemas_match_generated() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas");
    for (name, generated) in studio_types::schemas::all() {
        let path = dir.join(format!("{name}.json"));
        let checked_in: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display())),
        )
        .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));
        assert_eq!(
            checked_in, generated,
            "schemas/{name}.json has drifted from the types — run `just schemas`"
        );
    }
}

#[test]
fn every_checked_in_schema_is_registered() {
    // A schema file with no generating type would silently rot.
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas");
    let registered: Vec<String> = studio_types::schemas::all()
        .into_iter()
        .map(|(n, _)| format!("{n}.json"))
        .collect();
    for entry in std::fs::read_dir(&dir).expect("schemas/ exists") {
        let file = entry.unwrap().file_name().into_string().unwrap();
        assert!(
            registered.contains(&file),
            "schemas/{file} is not generated by studio_types::schemas::all()"
        );
    }
}
